# Ionita Alexandra-Mihaela 314CB

build:
	gcc -std=c99 -g -o tema1 main.c tema1.c
run:
	./tema1
clean:
	rm tema1
valgrind:
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./tema1